"""Builds models/toothcraft_cases.js for the interactive 3D viewer from the
anonymised sample set in SRC_BASE. Each case folder holds three 64^3 SDF
volumes (incomplete / sample / gt); this script turns each into a mesh and
packs all three into the TC02 binary format the page's decode() expects.

Usage: python models/build_cases.py
"""
import base64
import json
import os
import struct

import numpy as np

from lib_mesh import load_volume, mesh_from_volume, normalize_to_unit_cube

SRC_BASE = "/home/dejvax/PHD/ToothCraft/exps/normal/exps/saves/stellar-plant-183"
OUT_PATH = os.path.join(os.path.dirname(__file__), "toothcraft_cases.js")

# case folder -> FDI tooth number, read off the "Final_XX" segment of the name
CASES = [
    "N43_0073_U_Final_15.npy_132_samp0",
    "N43_0385_U_Final_17.npy_49_samp0",
    "N43_0769_U_Final_27.npy_72_samp0",
    "N43_0204_L_Final_31.npy_122_samp0",
    "N43_0532_L_Final_32.npy_121_samp0",
    "N43_0042_L_Final_33.npy_113_samp0",
    "N43_0755_L_Final_36.npy_112_samp0",
    "N43_0768_L_Final_36.npy_98_samp0",
    "N43_0607_L_Final_46.npy_62_samp0",
]

MESH_ORDER = ["incomplete.npy", "sample.npy", "gt.npy"]  # 0 = scan, 1 = ToothCraft output, 2 = technician design


def fdi_from_case(name):
    tag = name.split("Final_")[1]
    return int(tag.split(".")[0])


def encode_mesh(verts_unit, faces):
    q = np.clip(np.round((verts_unit + 1) / 2 * 65535), 0, 65535).astype("<u2")
    f = faces.astype("<u4")
    header = struct.pack("<II", q.shape[0], f.shape[0])
    return header + q.tobytes() + f.tobytes()


def build_case(folder):
    blobs = []
    focus_verts = None
    for fname in MESH_ORDER:
        vol = load_volume(os.path.join(SRC_BASE, folder, fname))
        verts, faces = mesh_from_volume(vol)
        verts_unit = normalize_to_unit_cube(verts)
        blobs.append(encode_mesh(verts_unit, faces))
        if fname == "incomplete.npy":
            focus_verts = verts_unit
    data = b"TC02" + b"".join(blobs)
    center = focus_verts.mean(axis=0)
    radius = float(np.linalg.norm(focus_verts - center, axis=1).max())
    return {
        "fdi": fdi_from_case(folder),
        "focus": [float(center[0]), float(center[1]), float(center[2]), radius],
        "data": base64.b64encode(data).decode("ascii"),
    }


def main():
    cases = [build_case(f) for f in CASES]
    cases.sort(key=lambda c: c["fdi"])
    with open(OUT_PATH, "w") as fh:
        fh.write("// Generated by models/build_cases.py from anonymised local-patch samples.\n")
        fh.write("// Per case: TC02 | 3 x [nv,nf u32 | pos u16x3 | idx u32x3]\n")
        fh.write("// Order: 0 = scan, 1 = ToothCraft output, 2 = technician design\n")
        fh.write("window.TOOTHCRAFT_CASES = ")
        fh.write(json.dumps(cases))
        fh.write(";\n")
    print(f"wrote {len(cases)} cases to {OUT_PATH}")


if __name__ == "__main__":
    main()
